/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lake.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.lake.model.lakes;
import com.lake.model.lakesModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the lakes service. Represents a row in the &quot;Sample_lakes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link lakesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link lakesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see lakesImpl
 * @see lakes
 * @see lakesModel
 * @generated
 */
@ProviderType
public class lakesModelImpl extends BaseModelImpl<lakes> implements lakesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a lakes model instance should use the {@link lakes} interface instead.
	 */
	public static final String TABLE_NAME = "Sample_lakes";
	public static final Object[][] TABLE_COLUMNS = {
			{ "lakeid", Types.INTEGER },
			{ "name", Types.VARCHAR },
			{ "url", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("lakeid", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("url", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table Sample_lakes (lakeid INTEGER not null primary key,name VARCHAR(75) null,url VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table Sample_lakes";
	public static final String ORDER_BY_JPQL = " ORDER BY lakes.lakeid ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Sample_lakes.lakeid ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.lake.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.lake.model.lakes"), true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.lake.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.lake.model.lakes"), true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.lake.service.util.PropsUtil.get(
				"lock.expiration.time.com.lake.model.lakes"));

	public lakesModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _lakeid;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setLakeid(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _lakeid;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return lakes.class;
	}

	@Override
	public String getModelClassName() {
		return lakes.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("lakeid", getLakeid());
		attributes.put("name", getName());
		attributes.put("url", getUrl());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer lakeid = (Integer)attributes.get("lakeid");

		if (lakeid != null) {
			setLakeid(lakeid);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String url = (String)attributes.get("url");

		if (url != null) {
			setUrl(url);
		}
	}

	@Override
	public int getLakeid() {
		return _lakeid;
	}

	@Override
	public void setLakeid(int lakeid) {
		_lakeid = lakeid;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getUrl() {
		if (_url == null) {
			return StringPool.BLANK;
		}
		else {
			return _url;
		}
	}

	@Override
	public void setUrl(String url) {
		_url = url;
	}

	@Override
	public lakes toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (lakes)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		lakesImpl lakesImpl = new lakesImpl();

		lakesImpl.setLakeid(getLakeid());
		lakesImpl.setName(getName());
		lakesImpl.setUrl(getUrl());

		lakesImpl.resetOriginalValues();

		return lakesImpl;
	}

	@Override
	public int compareTo(lakes lakes) {
		int primaryKey = lakes.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof lakes)) {
			return false;
		}

		lakes lakes = (lakes)obj;

		int primaryKey = lakes.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<lakes> toCacheModel() {
		lakesCacheModel lakesCacheModel = new lakesCacheModel();

		lakesCacheModel.lakeid = getLakeid();

		lakesCacheModel.name = getName();

		String name = lakesCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			lakesCacheModel.name = null;
		}

		lakesCacheModel.url = getUrl();

		String url = lakesCacheModel.url;

		if ((url != null) && (url.length() == 0)) {
			lakesCacheModel.url = null;
		}

		return lakesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{lakeid=");
		sb.append(getLakeid());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", url=");
		sb.append(getUrl());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.lake.model.lakes");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>lakeid</column-name><column-value><![CDATA[");
		sb.append(getLakeid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>url</column-name><column-value><![CDATA[");
		sb.append(getUrl());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = lakes.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			lakes.class
		};
	private int _lakeid;
	private String _name;
	private String _url;
	private lakes _escapedModel;
}