/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.river.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the rivers service. Represents a row in the &quot;Sample_rivers&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.river.model.impl.riversModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.river.model.impl.riversImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see rivers
 * @see com.river.model.impl.riversImpl
 * @see com.river.model.impl.riversModelImpl
 * @generated
 */
@ProviderType
public interface riversModel extends BaseModel<rivers> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rivers model instance should use the {@link rivers} interface instead.
	 */

	/**
	 * Returns the primary key of this rivers.
	 *
	 * @return the primary key of this rivers
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this rivers.
	 *
	 * @param primaryKey the primary key of this rivers
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the riverid of this rivers.
	 *
	 * @return the riverid of this rivers
	 */
	public int getRiverid();

	/**
	 * Sets the riverid of this rivers.
	 *
	 * @param riverid the riverid of this rivers
	 */
	public void setRiverid(int riverid);

	/**
	 * Returns the name of this rivers.
	 *
	 * @return the name of this rivers
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this rivers.
	 *
	 * @param name the name of this rivers
	 */
	public void setName(String name);

	/**
	 * Returns the url of this rivers.
	 *
	 * @return the url of this rivers
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this rivers.
	 *
	 * @param url the url of this rivers
	 */
	public void setUrl(String url);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.river.model.rivers rivers);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.river.model.rivers> toCacheModel();

	@Override
	public com.river.model.rivers toEscapedModel();

	@Override
	public com.river.model.rivers toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}